# fmt: off
CHROME_SEC_CH_UA_PLATFORM_WINDOWS = (
    ("0", "Windows"),
)

CHROME_SEC_CH_UA_PLATFORM_LINUX = (
    ("0", "Linux"),
)

CHROME_SEC_CH_UA_PLATFORM_ANDROID = (
    ("0", "Android"),
)

CHROME_SEC_CH_UA_PLATFORM_MACOS = (
    ("0", "macOS"),
)

CHROME_SEC_CH_UA_PLATFORM = {
    "windows": CHROME_SEC_CH_UA_PLATFORM_WINDOWS,
    "linux": CHROME_SEC_CH_UA_PLATFORM_LINUX,
    "android": CHROME_SEC_CH_UA_PLATFORM_ANDROID,
    "macos": CHROME_SEC_CH_UA_PLATFORM_MACOS,
}
# fmt: on
