# fmt: off
FIREFOX_SEC_CH_UA_PLATFORM_WINDOWS = (
    ("0", None),
)


FIREFOX_SEC_CH_UA_PLATFORM = {
    "windows": FIREFOX_SEC_CH_UA_PLATFORM_WINDOWS,
    "linux": FIREFOX_SEC_CH_UA_PLATFORM_WINDOWS,
    "android": FIREFOX_SEC_CH_UA_PLATFORM_WINDOWS,
    "mac": FIREFOX_SEC_CH_UA_PLATFORM_WINDOWS,
}
# fmt: on
